name: firstjob
on:
#  push: 
  workflow_dispatch:
    inputs:
      name:
        required: true
        description: your name please
        default: Raju
      last_name:
        required: true
        description: your last name please
        default: gadekar
jobs:
  firstecho:
    runs-on: ubuntu-latest
    env:
      Name: ${{inputs.name}}
      Last_name: ${{inputs.last_name}}
    steps:
      - name: print name
        run: echo "$Name"
      - name: print second msg
        run: echo "$Last_name"
      - name: Print all NAme
        run: echo " $Name $Last_name"
