name: firstjob
on:
  push: 
  workflow_dispatch:
jobs:
  firstecho:
    runs-on: ubuntu-latest
    steps:
      - name: print name
        run: echo "hello kapil"
      - name: print second msg
        run: echo " bye all "
